version: '3.8'

services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: db_aula
    ports:
      - "3307:3306"
    volumes:
      - ./carga.sql:/docker-entrypoint-initdb.d/carga.sql
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_app
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=passwd
      - DB_NAME=db_aula
    ports:
      - "3001:3000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge