version: '3.9'

services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: db_aula
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./carga.sql
        target: /docker-entrypoint-initdb.d/carga.sql
      # Outros volumes, networks e configurações de serviço podem ser adicionados aqui conforme necessário

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_app
    restart: always
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=passwd
      - DB_NAME=db_aula
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
